[profile.default]
src = 'contracts'
out = 'forge-artifacts'
libs = ['node_modules', 'lib']
test = 'test/foundry'
cache_path = 'forge-cache'
allow_paths = ['../', '../../pvt/lib/forge-std', '../../']
remappings = [
    'ds-test/=../../pvt/lib/forge-std/lib/ds-test/src/',
    'forge-std/=../../pvt/lib/forge-std/src/',
    '@balancer-labs/=../../node_modules/@balancer-labs/',
    '@swaap-labs/v2-errors/=../errors/',
    '@swaap-labs/v2-interfaces/=../interfaces/',
    '@chainlink/=../../node_modules/@chainlink',
    'hardhat/=../../node_modules/hardhat/'
]
optimizer = true
optimizer_runs = 9999
solc_version = '0.7.6'
ignored_error_codes = [8261]

[fuzz]
runs = 1000000
max_test_rejects = 6000000

[profile.intense.fuzz]
verbosity = 3
runs = 1000000
max_test_rejects = 6000000

[invariant]
runs = 10000
depth = 15
fail_on_revert = true

[profile.intense.invariant]
verbosity = 3
runs = 1000000
depth = 15
fail_on_revert = true