name: CI

env:
  CI: true

on:
  push:
    branches:
      - master
  pull_request:
    branches: ['*', '**/*']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Lint
        run: yarn lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Build
        run: yarn build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # balancer-v2 dependencies
  test-solidity-utils:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Compile
        run: yarn build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test
        run: yarn workspace @swaap-labs/balancer-v2-solidity-utils test

  test-standalone-utils:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Compile
        run: yarn build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test
        run: yarn workspace @swaap-labs/balancer-v2-standalone-utils test

  test-liquidity-mining:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Compile
        run: yarn build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test
        run: yarn workspace @swaap-labs/balancer-v2-liquidity-mining test

  # swaap-v2
  test-vault:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Compile
        run: yarn build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test
        run: yarn workspace @swaap-labs/v2-vault test
  
  test-pool-safeguard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Compile
        run: yarn build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test
        run: yarn workspace @swaap-labs/v2-pool-safeguard test

  test-errors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Compile
        run: yarn build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test
        run: yarn workspace @swaap-labs/v2-errors test

  test-swaap-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Compile
        run: yarn build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test
        run: yarn workspace @swaap-labs/v2-swaap-js test
